# Generated by Django 4.2.7 on 2024-05-01 17:22

from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=200, null=True)),
                ('file_title', models.CharField(max_length=200)),
                ('file_root', models.FileField(null=True, upload_to=file.models.user_file_path)),
                ('date_column', models.CharField(max_length=200, null=True)),
                ('start_index', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileStatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=200, null=True)),
                ('file_title', models.CharField(max_length=200)),
                ('file_root', models.FileField(null=True, upload_to=file.models.user_temp_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
        ),
        migrations.CreateModel(
            name='TempStatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TempStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.tempstatuscode')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.temp')),
            ],
        ),
        migrations.AddField(
            model_name='temp',
            name='statuses',
            field=models.ManyToManyField(through='file.TempStatus', to='file.tempstatuscode'),
        ),
        migrations.CreateModel(
            name='FileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.filestatuscode')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='statuses',
            field=models.ManyToManyField(through='file.FileStatus', to='file.filestatuscode'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
