export const abmsTextValue = {
  완숙토마토: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    줄기번호: "STEM_NO",
    초장: "PLLN",
    생장길이: "GRWT_LT",
    엽수: "FLG_YLD",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    줄기굵기: "STEM_DMT",
    화방높이: "FCLU_HG",
    화방번호: "FCLU_NO",
    화방별총개수: "TOTAL_PER_FCLU",
    화방별꽃수: "FCLU_FLWR_CO",
    화방별꽃봉오리수: "FCLU_BLM_CO",
    화방별개화수: "FCLU_FLAN_CO",
    화방별착과수: "FCLU_FRTST_CO",
    화방별적과수: "FCLU_FRTTHIN_CO",
    화방별수확수: "FCLU_HVST_CO",
    비고: "RM",
  },
  방울토마토: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    줄기번호: "STEM_NO",
    초장: "PLLN",
    생장길이: "GRWT_LT",
    엽수: "FLG_YLD",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    줄기굵기: "STEM_DMT",
    화방높이: "FCLU_HG",
    화방번호: "FCLU_NO",
    화방별총개수: "TOTAL_PER_FCLU",
    화방별꽃수: "FCLU_FLWR_CO",
    화방별꽃봉오리수: "FCLU_BLM_CO",
    화방별개화수: "FCLU_FLAN_CO",
    화방별착과수: "FCLU_FRTST_CO",
    화방별적과수: "FCLU_FRTTHIN_CO",
    화방별수확수: "FCLU_HVST_CO",
    비고: "RM",
  },
  딸기: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    액아구분: "AXBD_SE",
    초장: "PLLN",
    엽수: "FLG_YLD",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    엽병장: "LFST_LT",
    관부직경: "CROWN_DMT",
    화방번호: "FCLU_NO",
    화방출뢰기: "FCLU_BUDDING_DT",
    개화기일자: "BLPR_DATETM",
    화방별총개수: "TOTAL_PER_FCLU",
    화방별꽃수: "FCLU_FLWR_CO",
    화방별꽃봉오리수: "FCLU_BLM_CO",
    화방별개화수: "FCLU_FLAN_CO",
    화방별적화수: "FCLU_DEBLM_CO",
    화방별적과수: "FCLU_FRTTHIN_CO",
    화방별착과수: "FCLU_FRTST_CO",
    화방별수확수: "FCLU_HVST_CO",
    비고: "RM",
  },
  참외: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    초장: "PLLN",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    대목직경: "ROOTSTK_DMT",
    접수직경: "SCION_DMT",
    줄기굵기: "STEM_DMT",
    생장점경경: "GRWT_POINT_STEM_DMT",
    생장점절간장: "GRWT_POINT_JNT_CULN",
    엽록소: "CHLOROPHYLL",
    비고: "RM",
  },
  파프리카: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    줄기번호: "STEM_NO",
    초장: "PLLN",
    생장길이: "GRWT_LT",
    엽수: "FLG_YLD",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    줄기굵기: "STEM_DMT",
    화방높이: "FCLU_HG",
    본주구분: "FCLU_MAIN_STEM_SE",
    개화마디: "FLAN_JNT",
    착과마디: "FRTST_JNT",
    열매마디: "FRTS_JNT",
    수확마디: "HVST_JNT",
    마디별_꽃수: "JNT_FLWR_CO",
    마디별착과수: "JNT_FRTST_CO",
    마디별열매수: "JNT_FRUT_CO",
    마디별수확수: "JNT_HVST_CO",
    비고: "RM",
  },
  오이: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    덩굴구분: "VINE_SE",
    개체번호: "PPLT_NO",
    초장: "PLLN",
    마디번호: "JNT_NO",
    생장점길이: "GRWT_POINT_LT",
    줄기굵기: "STEM_DMT",
    절간장: "JNT_CULN",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    엽수: "FLG_YLD",
    엽상태: "FLG_STTUS",
    마디별_착과수: "JNT_FRTST_CO",
    마디별_열매수: "JNT_FRUT_CO",
    마디별_수확수: "JNT_HVST_CO",
    마디별_암꽃유무: "JNT_FEMALE_FLWR_ENNC",
    수확유무: "HVST_ENNC",
    열매상태: "FRUT_STTUS",
    생육과장곡선: "GRWH_FRUT_LT_CURVE",
    생육과장직선: "GRWH_FRUT_LT_SRTLNE",
    생육과폭: "GRWH_FRUT_BT",
    비고: "RM",
  },
  가지: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    줄기번호: "STEM_NO",
    개체번호: "PPLT_NO",
    초장: "PLLN",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    줄기굵기: "STEM_DMT",
    주경장: "STLN_HG",
    꽃수: "FLWR_CO",
    과실번호: "FRUT_NO",
    열매상태: "FRUT_STTUS",
    수확유무: "HVST_ENNC",
    비고: "RM",
  },
  국화: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    초장: "PLLN",
    엽수: "FLG_YLD",
    분지수: "BRNC_CO",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    줄기중앙직경: "STEM_CNTERR_DMT",
    개화기: "BLPR_DATETM",
    중심화제거일자: "CENT_FLWR_REMOV_DT",
    단일처리개시일: "",
    개화소요일: "CHSTHM_UNDEFINED",
    개화수: "FLAN_CO",
    비고: "RM",
  },
  수박: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    초장: "PLLN",
    마디수: "JNT_CO",
    엽수: "FLG_YLD",
    줄기굵기: "STEM_DMT",
    엽장: "LFLN",
    엽폭: "FLG_BT",
    엽병장: "LFST_LT",
    절간장: "JNT_CULN",
    착과절위: "FRTST_JNT_CO",
    착과율: "FRTST_RATE",
    수확율: "HVST_RATE",
    수확일수: "HVST_UNDEFINED",
    비고: "RM",
  },
  레드향: {
    농가명: "FRMHS_NM",
    조사일자: "EXAMIN_DATETM",
    개체번호: "PPLT_NO",
    발아기: "",
    개화기: "FLAN_DATETM",
    만개기: "",
    생리낙과: "",
    수관용적: "",
    생육과실크기_종경: "",
    생육과실크기_횡경: "",
    생육당도: "",
    생육산함량: "",
    생육과중: "",
    생육과피중: "",
    생육과피색: "",
    열과: "",
    이상낙과: "",
    비고: "RM",
  },
};

export const reviseDefaultValue = Object.freeze( [
  "전체_평균_",

  "주간_평균_",
  "주간_최소_",
  "주간_최대_",
  
  "야간_평균_",
  "야간_최소_",
  "야간_최대_",

  "주간_DIF_",
  "주간_GDD_",
  
  "일출전후2시간_온도차_",
  "일출부터정오_평균_",
]);