# Generated by Django 4.1.1 on 2023-02-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_name_alter_user_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_job',
            field=models.CharField(max_length=128, verbose_name='유저 직업'),
        ),
    ]
