services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "./init.sh"
    volumes:
      - .:/app
    expose:
      - "8001"
    networks:
      - nmh_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/templates
      - ./media:/media
    ports:
      - "8000:8000"
    depends_on:
      - django
      - next
    networks:
      - nmh_network

  redis:
    image: "redis:latest"
    container_name: redis
    command: redis-server --port 6379
    networks:
      - nmh_network

  next:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nmh_network

networks:
  nmh_network:


