# Generated by Django 4.2.7 on 2024-05-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(default=None, max_length=200)),
                ('model_name', models.CharField(default=None, max_length=200)),
                ('model_root', models.CharField(default=None, max_length=200)),
                ('model_meta_name', models.CharField(default=None, max_length=200)),
                ('model_meta_root', models.CharField(default=None, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
