# Generated by Django 4.2.7 on 2024-05-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_analytics', '0001_initial'),
        ('file', '0001_initial'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfeature',
            name='temp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='file.temp'),
        ),
        migrations.AddField(
            model_name='modelfeature',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_analytics.learnedmodel'),
        ),
        migrations.AddField(
            model_name='filefeature',
            name='file',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
