# Generated by Django 4.1.1 on 2022-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_after_db',
            name='file_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='file_before_db',
            name='file_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
