# Generated by Django 4.2.7 on 2024-02-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_last_login'),
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnedmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='modelfeature',
            name='feature_order',
        ),
        migrations.AddField(
            model_name='learnedmodel',
            name='model_meta_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='learnedmodel',
            name='model_root',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='learnedmodel',
            name='original_file_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='learnedmodel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='learnedmodel',
            name='model_meta_root',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='learnedmodel',
            name='model_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
