# Generated by Django 4.1.1 on 2023-02-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_db',
            name='file_Root',
            field=models.FileField(upload_to='file/<django.db.models.query_utils.DeferredAttribute object at 0x00000280A6FFF3D0>'),
        ),
    ]
