# Generated by Django 4.1.1 on 2022-11-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('smartfarm', '0002_file_after_db_file_type_file_before_db_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=200)),
                ('file_Title', models.CharField(max_length=200)),
                ('file_Root', models.FileField(upload_to='file/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='file_before_db',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='File_after_db',
        ),
        migrations.DeleteModel(
            name='File_before_db',
        ),
    ]
