# Generated by Django 4.2.7 on 2024-02-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0002_remove_learnedmodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_column',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='start_index',
            field=models.IntegerField(null=True),
        ),
    ]
