# Generated by Django 4.1.1 on 2023-02-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0002_alter_file_db_file_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_db',
            name='file_Root',
            field=models.FileField(upload_to='file/'),
        ),
    ]
